esphome:
  name: fujitsu

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components
    components: [fujitsu]

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

wifi:
  ssid: "your wifi ssid"
  password: "your wifi password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fujitsu"
    password: "a password for captive portal"

captive_portal:

climate:
  - platform: fujitsu
    name: "Fujitsu"
