esphome:
  name: fujitsu

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "your wifi ssid"
  password: "your wifi password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fujitsu"
    password: "a password for cative portal"



# Add the dependency to pull in the fujitsu heat pump component
external_components:
  - source: github://FujiHeatPump/esphome-fujitsu@proper-component


climate:
- platform: fujitsu_heat_pump
  name: My Fujitsu Heat Pump
  # The rest of these options are optional
  tx_pin: 2
  rx_pin: 3
  remote_temperature_id: some_temp_sensor # TODO see FujitsuClimate.cpp to correct the implementation
  master: false

# Pull a sensor in from homeassistant
sensor:
  - platform: homeassistant
    entity_id: sensor.zigbee_sensor
    id: some_temp_sensor

